# Generated by Django 3.1.1 on 2020-10-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='eanumber',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='eaverified',
        ),
    ]
