# Generated by Django 3.1.1 on 2020-10-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201001_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='eanumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
