# Generated by Django 3.1.1 on 2020-10-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_eanumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='eanumber',
        ),
    ]
