# Generated by Django 3.1.1 on 2020-10-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('profiles', '0006_auto_20201001_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceHubFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='NonRaceHubFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eanumber', models.CharField(blank=True, max_length=80, null=True)),
                ('eaverified', models.BooleanField(default=True)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('emergencycontactname', models.CharField(blank=True, max_length=60, null=True)),
                ('emergencycontactphone', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F'), ('N', 'Prefer not to say')], max_length=2, null=True)),
                ('tshirtsize', models.CharField(choices=[('Small', 'Small'), ('Med', 'Medium'), ('Large', 'Large')], default='Med', max_length=5)),
                ('club', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.club')),
                ('userprofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
    ]
