# Generated by Django 3.1.1 on 2020-10-01 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0007_nonracehubfriends_racehubfriends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonracehubfriends',
            old_name='userprofile',
            new_name='parentprofile',
        ),
        migrations.RemoveField(
            model_name='racehubfriends',
            name='userprofile',
        ),
        migrations.AddField(
            model_name='racehubfriends',
            name='parentprofile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='racehubfriends',
            name='racehubfriends',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.athleteprofile'),
        ),
    ]
