# Generated by Django 3.1.1 on 2020-10-01 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0012_auto_20201001_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racehubfriends',
            name='parentprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.athleteprofile'),
        ),
        migrations.AlterField(
            model_name='racehubfriends',
            name='racehubfriends',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
