# Generated by Django 3.1.1 on 2020-10-01 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20201001_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racehubfriends',
            old_name='parentprofile',
            new_name='rfathleteprofile',
        ),
        migrations.RenameField(
            model_name='racehubfriends',
            old_name='racehubfriends',
            new_name='rfuserprofile',
        ),
    ]
