# Generated by Django 3.1.1 on 2020-10-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_racehubfriends_myfriendsracehubid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racehubfriends',
            name='myfriendsracehubid',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
