# Generated by Django 3.1.1 on 2020-10-07 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20201002_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteprofile',
            name='userprofile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
        ),
    ]
