# Generated by Django 3.1.1 on 2020-10-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20201017_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonracehubfriends',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('N', 'Prefer not to say')], max_length=2, null=True),
        ),
    ]
