# Generated by Django 3.1.1 on 2020-09-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventinstance_race_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='exact_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
