# Generated by Django 3.1.1 on 2020-09-24 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_exact_distance_km'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='exact_distance_km',
            new_name='exactdistancekm',
        ),
    ]
