# Generated by Django 3.1.1 on 2020-09-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200924_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventinstance',
            old_name='event_date',
            new_name='eventdate',
        ),
        migrations.RenameField(
            model_name='eventinstance',
            old_name='friendly_name',
            new_name='friendlyname',
        ),
    ]
