# Generated by Django 3.1.1 on 2020-09-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200928_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinstance',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
