# Generated by Django 3.1.1 on 2020-09-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventinstance_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinstance',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
