# Generated by Django 3.1.1 on 2020-10-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventinstance_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='entrycutoff',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
