# Generated by Django 3.1.1 on 2020-10-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20201001_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinstance',
            name='eventdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
