# Generated by Django 3.1.1 on 2020-10-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20201002_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='entrycutoff',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
