# Generated by Django 3.1.1 on 2020-10-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20201002_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='entrycutoff',
            field=models.DateField(blank=True, null=True),
        ),
    ]
