# Generated by Django 3.1.1 on 2020-10-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20201002_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isvirtual',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
