# Generated by Django 3.1.1 on 2020-10-16 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20201005_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_instance',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventinstance'),
        ),
    ]
