# Generated by Django 3.1.1 on 2020-10-16 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20201016_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.discipline'),
        ),
        migrations.AlterField(
            model_name='event',
            name='distance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.distance'),
        ),
        migrations.AlterField(
            model_name='event',
            name='exactdistancekm',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='organiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.organiser'),
        ),
    ]
