# Generated by Django 3.1.1 on 2020-10-16 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20201016_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.format'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_post_code',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='eventinstance',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
