# Generated by Django 3.1.1 on 2020-10-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='eanumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
