# Generated by Django 3.1.1 on 2021-03-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20201022_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='which_athlete',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
